#!/usr/bin/env bash
#
# Copyright (C) 2023 Anders Logg
# Licensed under the MIT License
#
# Simple script for editing all core repos.

FILE="README.md"

for p in `cat utils/projects.csv`; do
    echo "Editing $FILE in $p"
    echo "---------------------------------------------------"
    cd ../$p
    $EDITOR $FILE
    cd ../dtcc
    echo ""
done
