#!/usr/bin/env bash
#
# Copyright (C) 2023 Anders Logg
# Licensed under the MIT License
#
# Simple script for pulling all core repos.

for p in `cat utils/projects.csv`; do
    echo "Pulling latest develop for $p"
    echo "---------------------------------------------------"
    cd ../$p
    git checkout develop
    git pull
    cd ../dtcc
    echo ""
done
