#!/usr/bin/env bash
#
# Copyright (C) 2023 Anders Logg
# Licensed under the MIT License
#
# Simple script for pushing all core repos.

for p in `cat utils/projects.csv`; do
    echo "Pushing latest develop in $p"
    echo "---------------------------------------------------"
    cd ../$p
    git push
    cd ../dtcc
    echo ""
done
